import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;

@Service
public class TransactionListener {

    @KafkaListener(topics = "${kafka.topic.transactions}", groupId = "midas-group")
    public void listen(ConsumerRecord<String, Transaction> record) {
        Transaction transaction = record.value();
        // At this stage, you are just receiving the transaction and doing nothing further
        System.out.println("Received Transaction: " + transaction);
    }
}

kafka:
  topic:
    transactions: transactions-topic
